# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swiftstack < Formula
  desc "High-speed project scaffolder using binary slices."
  homepage "https://github.com/004Ongoro/swiftstack"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/004Ongoro/swiftstack/releases/download/v0.1.0/swiftstack_darwin_amd64.tar.gz"
      sha256 "6d23d220f7d3bcc64e38ad88a60f31bec63c65b904bdf58d26a96ca29e07a830"

      def install
        bin.install "swiftstack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/004Ongoro/swiftstack/releases/download/v0.1.0/swiftstack_darwin_arm64.tar.gz"
      sha256 "725247beee8b7c0ad554ffad2e5cda641ee838ce0dcdbed5a44edc48a2ea3512"

      def install
        bin.install "swiftstack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/004Ongoro/swiftstack/releases/download/v0.1.0/swiftstack_linux_amd64.tar.gz"
      sha256 "6bde36f30849feac12bbb53542dc9ea5775d80d0ce05904e69af5e21c4cce8aa"
      def install
        bin.install "swiftstack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/004Ongoro/swiftstack/releases/download/v0.1.0/swiftstack_linux_arm64.tar.gz"
      sha256 "c2ae727f6a37b99b4ef42ed929a05749c62a8c5125e4328921491c6a3eada1d1"
      def install
        bin.install "swiftstack"
      end
    end
  end
end
