# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitaid < Formula
  desc "AI-powered git commit generator."
  homepage "https://github.com/004Ongoro/gitaid"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/004Ongoro/gitaid/releases/download/v0.1.2/gitaid_0.1.2_darwin_amd64.tar.gz"
      sha256 "f254ccd89137579f364e96fe6d7e3e9a433831b5b38d3020bc756459c8454e8c"

      def install
        bin.install "gitaid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/004Ongoro/gitaid/releases/download/v0.1.2/gitaid_0.1.2_darwin_arm64.tar.gz"
      sha256 "c78c6d101f829d42e69989a78da101d84a1514c263906f36367fb5a747fddc98"

      def install
        bin.install "gitaid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/004Ongoro/gitaid/releases/download/v0.1.2/gitaid_0.1.2_linux_amd64.tar.gz"
      sha256 "c286ee70ed9dcd254947269f7b6b8ea027d2afb38ca2c142e5e0b2efbe9c3b58"
      def install
        bin.install "gitaid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/004Ongoro/gitaid/releases/download/v0.1.2/gitaid_0.1.2_linux_arm64.tar.gz"
      sha256 "457abffb9b6cd59b3c0138e6434a91a325764c343cc3535f48fcdab4008466eb"
      def install
        bin.install "gitaid"
      end
    end
  end
end
