# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tidyup < Formula
  desc "A high-performance CLI tool to reclaim disk space from stale projects."
  homepage "https://github.com/004Ongoro/tidyup"
  version "0.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/004Ongoro/tidyup/releases/download/v0.7.3/tidyup_Darwin_x86_64.tar.gz"
      sha256 "e0db1070f906509210efbe978522f8008a561225d63e5b964d62edae08c4f344"

      def install
        bin.install "tidyup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/004Ongoro/tidyup/releases/download/v0.7.3/tidyup_Darwin_arm64.tar.gz"
      sha256 "07e3f4266ae828aebfc45ca781ec3bfccd0dba9c6989f74a17fceaf42c9243db"

      def install
        bin.install "tidyup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/004Ongoro/tidyup/releases/download/v0.7.3/tidyup_Linux_x86_64.tar.gz"
      sha256 "7fd3a043c94980f07989ce5cd83f6296a46a948279fe63fb36663865f2f3a053"
      def install
        bin.install "tidyup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/004Ongoro/tidyup/releases/download/v0.7.3/tidyup_Linux_arm64.tar.gz"
      sha256 "5d0d053924ce3f6937e27fb8c13b83b4b7cae6c07949c0757290f343c1e8b589"
      def install
        bin.install "tidyup"
      end
    end
  end
end
